 (function () {
  'use strict';
  var registry = new Map(), activeSession = null, boundBrowserPageLinks = new WeakSet(), resetters = [];
  window.registerBrowserReset = function (reset) { if (typeof reset === 'function') resetters.push(reset); };
  window.resetBrowserState = function () { activeSession = null; resetters.forEach(function (reset) { reset(); }); };
  document.addEventListener('click', function (event) { if (event.target.closest('[data-a="restart"],[data-dev="reset"]')) window.resetBrowserState(); }, true);
  window.registerBrowserPage = function (id, renderer) { if (!id || typeof renderer !== 'function') return false; registry.set(id, renderer); return true; };
  window.hasBrowserPage = function (id) { return registry.has(id); };
  window.showBrowserPage = function (page) { if (!activeSession || !page || !page.html) return false; activeSession.show(page); return true; };
  window.openBrowserPageById = function (id) { var renderer = registry.get(id); if (!renderer || !activeSession) return false; var page = renderer(); if (page && typeof page.then === 'function') { page.then(function (resolved) { window.showBrowserPage(resolved); }); return true; } return window.showBrowserPage(page); };
  window.bindBrowserPageLinks = function (root) { if (!root) return; root.querySelectorAll('[data-page-id]').forEach(function (element) { if (boundBrowserPageLinks.has(element)) return; boundBrowserPageLinks.add(element); element.addEventListener('click', function (event) { event.preventDefault(); event.stopPropagation(); if (!window.openBrowserPageById(element.dataset.pageId)) console.warn('[ARG Browser] Unhandled pageId:', element.dataset.pageId); }); }); };
  window.hydrateBrowserView = function (root) { window.bindBrowserPageLinks(root); if (typeof window.bindBrowserSearchView === 'function') window.bindBrowserSearchView(root); if (typeof window.bindBrowserZhaoView === 'function') window.bindBrowserZhaoView(root); if (typeof window.bindDarkwebAdminView === 'function') window.bindDarkwebAdminView(root); if (typeof window.bindDarkwebLogsView === 'function') window.bindDarkwebLogsView(root); };
  window.mountBrowserNavigation = function (container) { var observer = new MutationObserver(function () { var view = container.querySelector('.arg-browser-view'), address = container.querySelector('.arg-browser-address'); if (!view || !address || container.dataset.browserRuntimeNavigationBound) return; container.dataset.browserRuntimeNavigationBound = '1'; observer.disconnect(); var history = [], back = document.createElement('button'); back.type = 'button'; back.className = 'arg-browser-back'; back.setAttribute('aria-label', '返回上一页'); back.textContent = '←'; back.disabled = true; address.parentNode.insertBefore(back, address); activeSession = { show: function (page) { history.push({ html: view.innerHTML, address: address.textContent }); view.innerHTML = page.html; address.textContent = page.url; if (page.enhance) page.enhance(view); window.hydrateBrowserView(view); back.disabled = false; }, back: function () { var previous = history.pop(); if (!previous) return false; view.innerHTML = previous.html; address.textContent = previous.address; window.hydrateBrowserView(view); back.disabled = history.length === 0; return true; } }; back.addEventListener('click', function () { activeSession.back(); }); window.hydrateBrowserView(view); }); observer.observe(container, { childList: true, subtree: true }); };
  function normalise(value) { return String(value || '').trim().toLocaleLowerCase('zh-CN'); }
  function escape(value) { return String(value == null ? '' : value).replace(/[&<>\'"]/g, function (c) { return ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[c]; }); }
  function renderPage(page) { var blocks = (page.blocks || []).map(function (block) { return '<section class="arg-browser-page-block ' + escape(block.type || 'text') + '">' + (block.title ? '<h2>' + escape(block.title) + '</h2>' : '') + '<div>' + escape(block.content || '').replace(/\\n/g, '<br>') + '</div></section>'; }).join(''); return '<article class="arg-browser-site"><div class="arg-browser-site-url">' + escape(page.url || 'https://local.arg/') + '</div><h1>' + escape(page.title || '未命名页面') + '</h1>' + blocks + '</article>'; }
  function renderHome(data, state) { state.view.innerHTML = '<section class="arg-browser-home"><div class="arg-browser-brand"><i></i><b>Microsoft</b> ' + escape(data.brand || 'Bing') + '</div><nav>图片　视频　资讯　地图　学术　•••</nav><div class="arg-browser-search-wrap"><div class="arg-browser-tabs"><button type="button">国内版</button><button type="button">国际版</button></div><form class="arg-browser-form"><input autofocus aria-label="搜索" placeholder="' + escape(data.placeholder || '搜索') + '"><button aria-label="搜索" type="submit">⌕</button></form><div class="arg-browser-hot"><strong>你可能感兴趣</strong>' + (data.hotSearches || []).map(function (item) { return '<button type="button" data-query="' + escape(item) + '">' + escape(item) + '</button>'; }).join('') + '</div></div><p class="arg-browser-hint">本设备处于警局内网镜像环境，部分结果可能不可访问。</p></section>'; state.view.querySelector('.arg-browser-form').addEventListener('submit', function (event) { event.preventDefault(); state.search(event.currentTarget.querySelector('input').value); }); state.view.querySelectorAll('[data-query]').forEach(function (button) { button.onclick = function () { state.search(button.dataset.query); }; }); }
  window.ARG_BROWSER = { renderApp: function (container, deps) { deps.loadJson(deps.app.source + 'index.json').then(function (data) { data = data || {}; container.classList.add('arg-browser-container'); container.innerHTML = '<div class="arg-browser-toolbar"><button type="button" data-home aria-label="主页">⌂</button><span>内网浏览器</span><div class="arg-browser-address">arg://search</div></div><main class="arg-browser-view"></main>'; var view = container.querySelector('.arg-browser-view'); var state = { view: view, search: function (query) { query = String(query || '').trim(); if (!query) return renderHome(data, state); var wanted = normalise(query); var rule = (data.searchRules || []).find(function (item) { var keys = Array.isArray(item.keywords) ? item.keywords : [item.keyword]; return keys.some(function (key) { return normalise(key) === wanted; }); }); if (rule && data.pages && data.pages[rule.pageId]) { if (typeof window.openBrowserPageById === 'function' && window.openBrowserPageById(rule.pageId)) return; view.innerHTML = renderPage(data.pages[rule.pageId]); container.querySelector('.arg-browser-address').textContent = data.pages[rule.pageId].url || 'arg://page/' + rule.pageId; return; } view.innerHTML = '<section class="arg-browser-results"><div class="arg-browser-result-form"><input value="' + escape(query) + '"><button type="button">搜索</button></div><p>未找到与“' + escape(query) + '”相关的内网页面。</p><small>提示：只有已录入系统的关键词可以打开对应页面。</small></section>'; var form = view.querySelector('.arg-browser-result-form'); form.querySelector('button').onclick = function () { state.search(form.querySelector('input').value); }; form.querySelector('input').onkeydown = function (event) { if (event.key === 'Enter') state.search(event.currentTarget.value); }; }}; container.querySelector('[data-home]').onclick = function () { container.querySelector('.arg-browser-address').textContent = 'arg://search'; renderHome(data, state); }; renderHome(data, state); }).catch(function () { container.innerHTML = '<div class="win-empty"><strong>浏览器数据无法读取</strong></div>'; }); } };
}());
